### ISSUE TITLE
"X took a screenshot" notification does not appear on desktop client

### ISSUE THREAD

**Issue by mdPlusPlus** [oxen-io/session-desktop#2597] opened 2022-11-08 14:45 UTC
**Describe the bug**
On Android you get a notification in the chat if your direct message parter makes a screenshot: "[Name] took a screenshot"
This message does not appear when you're on the AppImage (and probably all desktop clients).

**To Reproduce**
Have two IDs, one on Android, one on AppImage, initiate a conversation and let the Android device make a screenshot at some point.
There will be no message about the screenshot on the desktop client. If you then use the same ID and "continue the session" on an Android device, you will see that there is a screenshot notification.

I think this is a privacy-critical bug that should be fixed ASAP.

**Comment by ianmacd** [comment] 2022-11-08 15:22
> I think this is a privacy-critical bug that should be fixed ASAP.

I agree that the inconsistent behaviour should be earmarked as a bug, but rooted Android devices can easily make Session screenshots without using the Android API, and PCs can make screenshots of desktop Session without any notification being sent to Android users.

The whole idea of informing users when a screenshot is made is unreliable and likely to result in a false sense of security.

**Comment by KeeJef** [comment] 2022-12-15 06:06
I'm getting proper screenshot notifications on Desktop when screenshot is taken on Android. Actually it seems that the Android device is sending too many notifications. Can anyone else reproduce? what Session versions are both devices?

**Comment by Bilb** [comment] 2023-01-24 02:26
So, we did a lot of testing and we cannot reproduce this issue.
We did every possibilities of each of the platform and it appeared to work as expected.
What we think was the original issue was that to have the X took a screenshot you need to enable the read receipts in the settings. Because it is a kind of read receipt in a sense.
 @mdPlusPlus could you please confirm to me that this happens even when both sides have the read receipts setting enabled?

**Comment by mdPlusPlus** [comment] 2023-01-24 14:46
I'm not able to reproduce it with my own devices anymore. The specific message in question is not in the swarm anymore. I might have generalized the "to reproduce" steps without verifying them. Sorry about that.  
I think what happened back then was me getting one of those "ghost" screenshot messages, were the partner actually didn't do a screenshot. At least I've read about that multiple times in the Communities. If those actually exist, it might have been one of those.

>What we think was the original issue was that to have the X took a screenshot you need to enable the read receipts in the settings. Because it is a kind of read receipt in a sense.

That's actually plausible, but I still think there's something up with occasional false screenshot messages, but that might not be related to this issue at all.  
Does the Android version enable read receipts by default?

**Comment by KeeJef** [comment] 2023-08-17 05:32
Cannot reproduce this issue, closing for now

**Closed by KeeJef** 2023-08-17 05:32 UTC
