### ISSUE TITLE
Temporary, revokeable, single use Session ID invites

### ISSUE THREAD

**Issue by lucy2812** [oxen-io/session-desktop#1879] opened 2021-08-21 23:08 UTC
Suggestion: Temporary, revokeable, single use Session ID invites.  

Why?  I want to keep my Session ID from being tracked, correlated, distributed.

**Comment by eyeberic** [comment] 2021-08-22 00:02
Dupe of #1688 ; Long-term solution would be #1809 .

**Closed** 2021-08-22 23:53 UTC
