### ISSUE TITLE
Windows defender detects as cryptocurrency miner/ Pup

### ISSUE THREAD

**Issue by Drakesdrs** [oxen-io/session-desktop#1674] opened 2021-06-01 16:08 UTC
**Describe the bug**
Windows defender detects session as a literal coinminer.
*I am not accusing session to be a miner but like how can windows defender be so bad that it detects foss as a PUP*

**To Reproduce**
1. Turn on windows defender
2. download at https://getsession.org/windows
3. try to execute the file

**Screenshots or Logs**
<img width="302" alt="Sfwe6s" src="https://user-images.githubusercontent.com/67423571/120356126-e9cc6b00-c2fb-11eb-9da0-fc73d0ff046e.png">

**Other information (please complete the following information):**

* Device: Personal computer
* OS: Windows 10
* 1.6.3

**Comment by Bilb** [comment] 2021-06-01 23:42
This is a duplicate of https://github.com/oxen-io/session-desktop/issues/1460
Hopefully, this issue will be fixed with the next release as we removed some code which might have been falsy flagged as coinminer. A test on virustotal tells me the next release should be fixed.

@Drakesdrs in the meantime could you try with this unofficial release (please don't install it) and let me know if the coinminer warning is still there on your windows?
https://jirafeau.net/f.php?h=2sbI-6Et&d=1

**Closed** 2021-06-01 23:42 UTC
