### ISSUE TITLE
Session wants message request approval for an attachment to Note-to-self.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2201] opened 2022-03-11 01:05 UTC
**Describe the bug**

The new message request interface needs to treat Note-to-self as a special case.

**To Reproduce**

Try to send yourself an attachment via Note-to-self. Session will complain `You cannot send attachments until the conversation is approved.`

Not only is it illogical to require approval, but there seems to be no way to explicitly give that approval either.

**Comment by KeeJef** [comment] 2022-08-10 08:19
I cant reproduce this, does this only happen when the attachment is the first message or is this fixed in the current version?

**Comment by KeeJef** [comment] 2023-02-03 04:52
Closing due to lack of info

**Closed by KeeJef** 2023-02-03 04:52 UTC
