### ISSUE TITLE
(requirement) group hub

### ISSUE THREAD

**Issue by sakurayz** [oxen-io/session-desktop#2409] opened 2022-08-09 11:10 UTC
It is recommended to add a group hub to centralize the open group & close group in app or one website.
Or add the function of searching group.

General users cannot create open groups, which is not conducive to promoting session app, and feels that there are too few users.

**Comment by KeeJef** [comment] 2022-12-13 05:27
Closing as duplicate of #2235

**Closed by KeeJef** 2022-12-13 05:27 UTC
Labels: enhancement
