### ISSUE TITLE
Create Thread

### ISSUE THREAD

**Issue by Pantyhose-X** [oxen-io/session-desktop#2450] opened 2022-08-28 00:54 UTC
Allow users to Liberty Create Thread
Thread time, for 1 year. or forever
Only groups, administrators and creators, can Remove Thread channels
![](https://support.discord.com/hc/article_attachments/4405086336279/threads_demo_gif.gif)
Session can feel like an ocean sometimes with walls of text rapidly flooding your screen. Interesting conversations can be confusing to follow in the middle of other conversations and may just disappear entirely.

**Comment by secularaloha** [comment] 2022-11-23 15:23
Threaded conversations should be high on the list. Some conversations I want to follow and others not so much.

**Comment by KeeJef** [comment] 2022-12-13 05:49
Closing as duplicate of #1119 , we aren't aiming to support threads currently but will keep these issues updated if we change the focus

**Closed by KeeJef** 2022-12-13 05:49 UTC

**Comment by Pantyhose-X** [comment] 2022-12-27 13:32
How to compete with revolt/Cabal/discord/ without Thread Session
session answering repetitive questions numerous times a day
Session has to read a lot of spam every day
Session no Thread for small team chat with 100 people
