### ISSUE TITLE
[Feature Request] Ability to collapse / expand contacts list

### ISSUE THREAD

**Issue by BeholdersEye** [oxen-io/session-desktop#2752] opened 2023-05-08 21:13 UTC
I would like the option of collapsing the contacts list and using more of the window to display the conversation.

I have attached three images to show what I have in mind. 

The first shows Session's current layout on desktop.

![Session current default layout on desktop](https://user-images.githubusercontent.com/13533723/236934568-5322a3a3-47d9-42d8-b2bc-7794b357214b.png)

The second and third show an added button, colored orange that would hide / show the contacts panel. This is only a mockup, I am sure it could be made more appealing. Probably the "Conversations" header should collapse too but I don't want to remake the mockup so use your imagination.

![proposed contact list expanded](https://user-images.githubusercontent.com/13533723/236934632-f56124db-cb61-4dff-a020-7cd1da735068.png)

![proposed contact list collapsed](https://user-images.githubusercontent.com/13533723/236934725-1fa92e50-9102-460b-ba60-94222386961a.png)

Thank you for reading this.

**Comment by Bilb** [comment] 2023-05-15 00:00
Duplicate of https://github.com/oxen-io/session-desktop/issues/2492

**Closed by Bilb** 2023-05-15 00:00 UTC
