### ISSUE TITLE
[Feature] <title>Finding Proxy Solutions in Linux for Firewall-Constrained Apps like Session 

### ISSUE THREAD

**Issue by wangyifan349** [oxen-io/session-desktop#2888] opened 2023-08-28 01:38 UTC
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

If you're using software like Session, Jami, or similar applications on a Linux system, and it appears that these programs do not support standard proxies, and you also cannot disable the firewall due to implementing a Kill Switch within the firewall, you're wondering how to address this issue. This is because you need proxy functionality but are unable to configure it.

### Anything else?

I expect these apps to add support for proxies like HTTPS and SOCKS5.

**Comment by KeeJef** [comment] 2023-08-28 05:17
Closing as duplicate of https://github.com/oxen-io/session-desktop/issues/1557

**Closed by KeeJef** 2023-08-28 05:17 UTC
Labels: enhancement
