### ISSUE TITLE
[Feature Request] Allow a Poster to Edit their own Posted Message

### ISSUE THREAD

**Issue by JustaNormalGuy230** [oxen-io/session-desktop#2503] opened 2022-09-18 06:15 UTC
In a session, allow a user the ability to go back to a particular message and edit it, if they are the original poster.  Editing just the message text would be a big improvement.  I'm aware that if your post is the last one in a session, a simple trick is to Copy the Message Text, delete the message, then post the modified message [text], but this will not maintain the [chronological] order of the message if the message is (say) 5 messages ago.  Also, I'm aware that this could be quite difficult to implement with the use of disappearing messages and knowing when it is no longer possible to edit a message that has disappeared...

If this is difficult to implement, since most post editing is for typos, beefing up the dictionary/grammar engines and/or allowing the post to progress to a WYSIWYG Window to see what the post will be like and to make changes before actually releasing/sending it, would be useful...

I apologize if this has been previously discussed or there is a way to do it, but I could find no mention of it in a search.  I'm sure it was thought about but it would be nice to mention that it's not implemented and why in the FAQ.  Many users (including those that use the Phone App Clients) have asked me if it's possible, so an explanation even here would be useful, thanks.

**Comment by KeeJef** [comment] 2022-12-14 00:38
Closing as duplicate of #885 , Editing messages in Communities should be fairly easy to implement, we actually already have the endpoints for it finished in PySOGS, just not implemented clientside yet, editing in 1-1 and groups/closed groups is a little trickier.

**Closed by KeeJef** 2022-12-14 00:38 UTC
