### ISSUE TITLE
[Feature Request] Start Session On System Login

### ISSUE THREAD

**Issue by elibroftw** [oxen-io/session-desktop#2034] opened 2021-11-16 22:06 UTC
A feature Discord, Matrix and even my music player is that they can start minimized to the tray after logging into the system.
Since you guys use electron, https://www.electronjs.org/docs/latest/api/app#appsetloginitemsettingssettings-macos-windows.

**Comment by KeeJef** [comment] 2023-02-03 04:43
closing as duplicate of https://github.com/oxen-io/session-desktop/issues/2258

**Closed by KeeJef** 2023-02-03 04:43 UTC
Labels: enhancement
