### ISSUE TITLE
disappearing messages notification is false

### ISSUE THREAD

**Issue by InoMurko** [oxen-io/session-desktop#1574] opened 2021-04-18 09:16 UTC
This keeps on appearing even though none of the parties in the conversation actually changed the settings.

<img width="686" alt="Screenshot 2021-04-18 at 11 14 40" src="https://user-images.githubusercontent.com/2582555/115140412-76b2b200-a037-11eb-8c32-f1f7b7602da6.png">

**Comment by Norbert80** [comment] 2021-05-08 18:19
Do you use your (the same) ID on more than one devices?

**Comment by InoMurko** [comment] 2021-05-12 08:29
Yes

**Comment by Norbert80** [comment] 2021-05-12 09:02
@InoMurko thanks for your reply. I run into similar trouble with same ID in Android and Desktop. I also had these permanent ghost timer changes as well as additional issues. I have filed:
https://github.com/oxen-io/session-android/issues/513

However I have not tried multi-device again because I don't want to destroy my private groups again and again...

In the recent releases the developer team promised improvements to make private groups more robust. From which build did you take the screenshot above? I guess it is also a private group?

Did you also check recent builds from github on both devices?

**Comment by InoMurko** [comment] 2021-05-12 09:46
@Norbert80 the screenshot was taken from a 1:1 conversation. I'm not part of any private groups (just fyi - perhaps it's important).

I too did not use multidevice for a while, but Telegram said that multidevice stuff is now fixed. So I started using that.

But session on ios is very flaky, sometimes desktop on mac too. at the moment, random push notifications are still a concern.

**Comment by KeeJef** [comment] 2021-08-10 08:11
We have made quite a few changes to closed groups and disappearing messages , has this occurred since then?

**Comment by Norbert80** [comment] 2021-08-15 08:53
Unfortunately, I can't say at this time if the problem is fixed now. Since I had this problem, I no longer use larger groups on Session. Also, I no longer use the disappearing message timer for groups.


My suggestion is to close this issue. If the problem occurs again it can be reopened.

**Closed** 2021-09-27 23:51 UTC
