### ISSUE TITLE
Feature Request:  Increase disappearing message timer

### ISSUE THREAD

**Issue by lucy2812** [oxen-io/session-desktop#2177] opened 2022-02-19 06:55 UTC
I would like the peace of mind that I don't have forever messages out there.

I want a setting to make disappearing messages the default for all contacts.

Maybe 1 month is a good amount of time.

**Comment by Bilb** [comment] 2022-04-14 06:14
by out there, you mean on your recipient device?
because messages aren't stored more than 14 days on the network already

**Comment by KeeJef** [comment] 2022-08-10 07:42
Closed as duplicate of https://github.com/oxen-io/session-desktop/issues/383

**Closed by KeeJef** 2022-08-10 07:42 UTC
