### ISSUE TITLE
[BUG] <title>it takes forever to load audio, video, image lately

### ISSUE THREAD

**Issue by StacyAceIt** [oxen-io/session-desktop#3123] opened 2024-07-15 01:05 UTC
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This issue started in recent few weeks. 

### Expected Behavior

These used to be able to load without much effort

**Comment by KeeJef** [comment] 2024-07-29 07:11
Hey @StacyAceIt we released a new version of Session (1.12.5) recently which should resolve this issue, please let me know if the problem isn't fixed once you've upgraded.

**Closed by KeeJef** 2024-07-29 07:11 UTC
Labels: bug

**Comment by StacyAceIt** [comment] 2024-08-02 00:49
The addressed issues are fixed, thanks! I also wish session will let us upload larger files one day.
