### ISSUE TITLE
Session fails to build onion path, and remains stuck even after restart

### ISSUE THREAD

**Issue by eyeberic** [oxen-io/session-desktop#1886] opened 2021-08-25 10:25 UTC
### Describe the bug

Session just stops trying to fetch nodes to build the onion path for routing, and remains stuck there with no attempts to retry. 

Even after killing and restarting Session, the same result. 

However, if you delete local data, and restore your account via the recovery phrase, the path gets built as per normal, and chats get synced downstream to the local storage. 

The issue is duplicate-able: If you copy the "Session" folder from where the AppImage stores the user data by default (`$HOME/.config/Session/`), into an [AppImage portable mode directory](https://docs.appimage.org/user-guide/portable-mode.html#example), you retain the user data and experience the same issue. 

### To Reproduce

N.A: Unable to pinpoint any exact cause of this Issue. 

### Screenshots or Logs

[log.log](https://github.com/oxen-io/session-desktop/files/7046151/log.log)

### Other information (please complete the following information):

* Device: Linux
* OS: Ubuntu 18.04.01
* Session Version or Git commit hash: 1.6.11

**Comment by eyeberic** [comment] 2021-08-31 01:19
Since my last post, I have been using the AppImage in portable mode as mentioned in the original post, and have encountered the issue twice. 

Since the logs mentions about not being able to fetch more nodes, I tried restarting my firewall service, and it seems to resolve it. 

Perhaps there is some form of resource exhaustion in that area too?

**Comment by laurin-1** [comment] 2021-09-01 14:38
I also just had this bug again, it seems to happen every time the client can't reach an open group it was previously connected to, last time it apparently was because the OSINT group went down, and now three open groups from Vector are down which I was a member of, hope this helps with finding the cause of the bug.

**Comment by Bilb** [comment] 2021-09-06 07:00
Could you try the 1.7.0 and send me your first startup logs?

**Comment by ianmacd** [comment] 2021-09-06 07:49
> Could you try the 1.7.0 and send me your first startup logs?

Working for me. Many thanks.

**Comment by ianmacd** [comment] 2021-09-06 16:05
1.7.0 fixed my Windows machine, but now my Linux machine has been broken by the new version.

I see the code fix increased the number of nodes from 12 to 13, and in my broken client's log, I see that I am indeed now pulling 13 nodes from the DB, so it seems as if I'm now simply hitting the new limit.

Log attached.

[log.log](https://github.com/oxen-io/session-desktop/files/7117058/log.log)

**Comment by JustVictor17** [comment] 2021-09-09 23:18
1.7.0 does suffer the same issue for me
Is there a workaround...?

**Comment by Bilb** [comment] 2021-09-10 00:03
I am working on a fix

**Comment by Bilb** [comment] 2021-09-14 01:11
Should be fixed in 1.7.1

**Closed by Bilb** 2021-09-14 01:11 UTC

**Comment by ianmacd** [comment] 2021-09-14 07:45
> Should be fixed in 1.7.1

Cheers. I don't currently have a stuck client, so I can't verify that at the moment, but I will certainly let you know if I encounter the bug again.

**Comment by me-chrislang** [comment] 2021-09-15 10:20
> Should be fixed in 1.7.1

Still facing a same issue
```
Invalid ciphertext
```
