### ISSUE TITLE
Disappearing messages not enabled on new devices

### ISSUE THREAD

**Issue by AlexHasNoFace** [oxen-io/session-desktop#2353] opened 2022-05-29 11:28 UTC
**Describe the bug**
If a new device is setup to sync with a session ID, then messages up to 14 days old (which are deleted on the other device because they expired) get downloaded onto the new device, and there is no disappearing messages timer at all.

**To Reproduce**
1. Make a session ID on phone
2. Enable disappearing messages with someone, and wait 14 days (for the disappearing messages notice to expire)
3. Start sending them messages, wait for all the messages to expire, and be deleted on the phone
4. Enter the recovery phrase onto a desktop, to sign in to the session ID
5. All the deleted messages, going back 14 days, are synced to the desktop. There is no disappearing messages timer on the desktop. For the phone and the other side of the conversation, it looks like disappearing messages is enabled and functional. 

**Other information (please complete the following information):**

* Device: Android & Linux desktop x86_64
* OS: Android 12 & Linux Kernel 5.15.41
* Session Version or Git commit hash: for Android 1.13.1; for Desktop v1.8.6

**Comment by KeeJef** [comment] 2022-08-11 06:32
Duplicate of #2048

**Closed by KeeJef** 2022-08-11 06:32 UTC
