### ISSUE TITLE
Unhandled Error  Error: ENOENT: no such file or directory, open '/home/user/.config/Session/logs/log.log'

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#2333] opened 2022-05-19 06:41 UTC
**Describe the bug**

On Debian 11 bullseye session-desktop-linux-x86_64-1.8.4.AppImage was updated:
"Update installer has already been triggered. Quitting application."

Then after some time I have seen:

> Unhandled Error Error: ENOENT: no such file or directory, open '/home/user/.config/Session/logs/log.log'

This file does not exist indeed, first existing in that path is:

$ ls -lh /home/user/.config/Session/
```
total 68K
drwxr-xr-x 258 user user 4.0K May 18 14:35  attachments.noindex
drwx------   3 user user 4.0K May 18 09:35  blob_storage
drwx------   2 user user 4.0K May 18 09:35  Cache
drwx------   4 user user 4.0K May  3 21:38 'Code Cache'
-rw-r--r--   1 user user  107 May 18 09:35  config.json
drwx------   2 user user 4.0K May 18 09:35  Crashpad
drwx------   2 user user 4.0K May  3 21:38 'Crash Reports'
drwx------   2 user user 4.0K May  3 21:38  Dictionaries
-rw-r--r--   1 user user  164 May 18 09:35  ephemeral.json
drwx------   2 user user 4.0K May  3 21:38  GPUCache
drwx------   3 user user 4.0K May  3 21:38 'Local Storage'
-rw-------   1 user user  619 May 19 08:31 'Network Persistent State'
-rw-------   1 user user   97 May  3 21:38  Preferences
drwx------   2 user user 4.0K May 19 08:31 'Session Storage'
drwx------   3 user user 4.0K May 15 22:47  shared_proto_db
drwxr-xr-x   2 user user 4.0K May 19 08:31  sql
drwx------   2 user user 4.0K May 15 22:47  VideoDecodeStats
```
'Crash Reports' is empty...

I see that the appimage file was removed and there is 1.8.5 file now.

**Comment by ianmacd** [comment] 2022-05-19 07:09
This is a duplicate of #2278.

**Closed** 2022-08-11 05:34 UTC
