### ISSUE TITLE
Window Doesnt Auto Scroll From New Messages

### ISSUE THREAD

**Issue by Ruok2bu** [oxen-io/session-desktop#2735] opened 2023-04-12 17:19 UTC
**Describe the bug**
When i receive a new message, the window doesnt auto scroll down to the bottom. I have to manually scroll. This happens when im typing a message and when im not typing a message.

**To Reproduce**
Start chat with someone, they type things and send. Window doesnt scroll down.

**Screenshots or Logs**
N/A

**Other information (please complete the following information):**

* Device: PC
* OS: Linux Mint 21.1
* Session Version or Git commit hash: v1.10.8

**Comment by KeeJef** [comment] 2023-04-14 05:43
Closing as duplicate of https://github.com/oxen-io/session-desktop/issues/2632

**Closed by KeeJef** 2023-04-14 05:43 UTC
