### ISSUE TITLE
Copy/paste linebreak

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1758] opened 2021-07-02 13:32 UTC
I just copied text from a message in an open group, containing line breaks.

When I went to paste it, all the line breaks are replaced by "" (nothing)

**Comment by peepopoggers** [comment] 2021-07-03 20:17
![image](https://user-images.githubusercontent.com/72892531/124365982-f833dc80-dc43-11eb-8919-29663542e73d.png)

It might be a text display issue compared to an actual input issue, as i was able to copy what you typed without issue.

**Comment by peepopoggers** [comment] 2021-07-03 20:18
![image](https://user-images.githubusercontent.com/72892531/124366010-329d7980-dc44-11eb-8a43-95b801bd0e22.png)

Confirmed to happen when you select text with cursor. When using "copy text" button this does not happen.

**Comment by Bilb** [comment] 2021-08-20 03:40
Should be fixed in 1.6.11

**Comment by Bilb** [comment] 2021-08-23 05:35
Reopening as it works for message sent by someone else, but it looks like message sent by yourself gets all new line removed

**Comment by Bilb** [comment] 2021-09-27 23:50
Fixed in 1.7.3

**Closed by Bilb** 2021-09-27 23:50 UTC
Labels: bug
