### ISSUE TITLE
Clicking quoted/cited post jumps above, but unable to go back to where i was. Add back button/action or links to replies.

### ISSUE THREAD

**Issue by slrslr** [oxen-io/session-desktop#2721] opened 2023-03-31 14:37 UTC
When someone quote/cite earlier post i can click the quotation and jump to that post. That is handy.
I read that post and want to return back where i was.
Though when the original location was not on the bottom, but deep in the long timeline of the community, i am unable to easily get back to where i was. Sometimes i spend 10-20 second+.

PROPOSALS:
a) display back arrow button near the post to which i have jumped
b) display links to posts which quote every post (links to post replies, possibly link title can be username shortened to lets say 5 characters)
C) assign Backspace key the "back" action

**Other information (please complete the following information):**

* Device: PC
* OS: Debian
* Session Version or Git commit hash: 1.10.7

**Comment by KeeJef** [comment] 2023-08-18 06:56
Duplicate of https://github.com/oxen-io/session-desktop/issues/1997

**Closed by KeeJef** 2023-08-18 06:56 UTC
Labels: enhancement
