### ISSUE TITLE
After the update to 1.6.9, when adding someone in an open group, the Session ID is not "resolved" into the nickname

### ISSUE THREAD

**Issue by laurin-1** [oxen-io/session-desktop#1815] opened 2021-07-30 11:28 UTC
When adding(@) someone in an open group after the update to 1.6.9, their Session ID is not "resolved" to their nickname, instead its displayed as (...xxxxxx), where xxxxxx is the last six characters of their Session ID(see screenshot).
![image](https://user-images.githubusercontent.com/87230375/127646488-3910a01c-ee26-4e12-a01a-e7d8c8444b48.png)

This was noticed by another user and I can confirm it.
This didn't happen with 1.6.7, it's only the case after updating to 1.6.9.
I'm using the package from the repo on Debian bullseye, version 1.6.9.

**Comment by KeeJef** [comment] 2021-08-03 05:57
Did also notice that some users mentions seem to be displaying as the full Session ID 
![image](https://user-images.githubusercontent.com/27277414/127965282-73ae3466-4883-4be6-aad2-dd43897cdfcd.png)

**Comment by laurin-1** [comment] 2021-08-03 08:43
@KeeJef What you're describing usually happens from my experience when using emojis and @dding someone in the same message.

**Comment by Bilb** [comment] 2021-08-04 05:44
@laurin-1 thanks, it helped a lot to find the root cause of this issue.

**Comment by Bilb** [comment] 2021-08-05 04:30
Both issues should be fixed in 1.6.10

**Closed by Bilb** 2021-08-05 04:30 UTC
Labels: bug
