### ISSUE TITLE
Wierd transformation of emojis

### ISSUE THREAD

**Issue by kleinpetr** [oxen-io/session-desktop#2014] opened 2021-11-07 18:23 UTC
**Describe the bug**
Bad transforming chars to emojis

**To Reproduce**
type `:)` and it is transformed like a `:D` emoji

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/17269309/140657015-02d66cd7-d6dc-42ee-85ec-9af8df24c04b.png)

**Other information (please complete the following information):**

* Device: ThinkPad T470
* OS: PopOS! 21.04
* Session Version: v1.7.4

**Comment by peepopoggers** [comment] 2021-11-10 23:02
IMO :) and :D should be replaced with (in order):
![image](https://user-images.githubusercontent.com/72892531/141207623-4509e3cf-dc55-4b9d-ab5c-0ba2620c620a.png)

**Comment by sambhavsaggi** [comment] 2021-11-29 02:19
Duplicate of #1453

**Comment by peepopoggers** [comment] 2021-11-29 08:01
@sambhavsaggi This is not a duplicate of that issue, the symbols convert wrongly (when enabled even if an option was given)

**Comment by Bilb** [comment] 2022-04-14 06:18
We are now using unicode for emojis. So this issue should be fixed.

Feel free to reopen if needed

**Closed by Bilb** 2022-04-14 06:18 UTC
Labels: bug
