### ISSUE TITLE
SOGS link 

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#2763] opened 2023-05-21 08:53 UTC
![image](https://github.com/oxen-io/session-desktop/assets/122599546/8108d6d4-daa4-4d08-815b-ef929834c81a)

when SOGS link is clicked in the app, it suggests to copy it or open in browser. session should recognize sogs links and suggest (instead of opening in browser) to join the SOGS for two reasons:
1. its more handy and beautiful
2. when a new user opens SOGS link, clicks "open in browser" and sees an error ("The requested URL was not found on the server"), they might think, that the SOGS just doesn't work. wrote about this problem [here](https://github.com/oxen-io/session-desktop/issues/2754).

**Comment by Bilb** [comment] 2023-05-24 23:58
Duplicate of https://github.com/oxen-io/session-desktop/issues/1072

**Closed by Bilb** 2023-05-24 23:58 UTC
