### ISSUE TITLE
[Feature] Mark gifs

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#3132] opened 2024-07-28 21:39 UTC
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

Gifs should either start without being opened in full screen, or marked to be separated from basic photos (because you might miss an animated image in a lot of separated images sent)

**Comment by KeeJef** [comment] 2024-07-29 06:11
Closing as a duplicate of https://github.com/oxen-io/session-desktop/issues/2968

**Closed by KeeJef** 2024-07-29 06:11 UTC
Labels: enhancement
