### ISSUE TITLE
[BUG] <down arrow appearing even when at bottom of buffer>

### ISSUE THREAD

**Issue by dave15559546** [oxen-io/session-desktop#2783] opened 2023-06-12 00:30 UTC
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

even when at the bottom of the buffer of text, the down arrow sometimes appears 

clicking on it will remove it but if I scroll up and back down it still shows up again potentially obscuring text

I can't always reproduce this but it happens pretty often

here's a screenshot
![image](https://github.com/oxen-io/session-desktop/assets/6696534/6912e5c6-54b5-495d-b365-ea9eef328558)

### Desktop Version

v1.10.8 - windows 10 version 1809

**Comment by Bilb** [comment] 2023-07-03 06:54
Duplicate of #2751

**Closed by Bilb** 2023-07-03 06:54 UTC
Labels: bug
