### ISSUE TITLE
Message delay in the main box

### ISSUE THREAD

**Issue by User-McUserface** [oxen-io/session-desktop#2685] opened 2023-02-18 18:46 UTC
Latest Session desktop on Win 11.

First few words appear on the left, in the conversations column preview, but then it can take 3-5 seconds until that same message shows up in the conversation thread view.

**Comment by KeeJef** [comment] 2023-04-14 07:10
Cannot reproduce, is it possible to show a screen recording of the issue?

**Comment by User-McUserface** [comment] 2023-06-20 09:39
Tried to reproduce on the latest version.

I can still notice that the preview and main window are not fully synchronized in displaying the message content but the delay is nowhere near what it used to be when I opened this issue.

Will keep an eye on it.

**Comment by KeeJef** [comment] 2023-08-18 05:00
Closing this one, looks these are well synced for me

**Closed by KeeJef** 2023-08-18 05:00 UTC
Labels: bug
