### ISSUE TITLE
session not working at whonix

### ISSUE THREAD

**Issue by officerhi** [oxen-io/session-desktop#2764] opened 2023-05-23 01:03 UTC
normal id identifies but I can't send any message

**Comment by officerhi** [comment] 2023-06-13 02:43
Is there anyone who can help?

**Comment by Bilb** [comment] 2023-07-03 06:41
did you get a path at all? green or red dot on the bottom left?
I suppose whonix uses a proxy to root the network out, but Session does not support running through a proxy currently

**Comment by Bilb** [comment] 2023-07-03 06:42
Duplicate of #2712 #1139

**Closed by Bilb** 2023-07-03 06:42 UTC

**Comment by officerhi** [comment] 2023-07-04 04:20
As far as I understand, I'll have to wait for proxy support. so how long does this take? do you have an idea?
